explore_node:
  ros__parameters:
    # Frame configuration (REQUIRED)
    robot_base_frame: base_link
    global_frame: map
    
    # Costmap topics (REQUIRED)
    costmap_topic: global_costmap/costmap
    costmap_updates_topic: global_costmap/costmap_updates
    
    # Exploration behavior
    return_to_init: false            # Don't return to start position
    visualize: true                  # Show frontiers in RViz for debugging
    
    # Timing parameters (OPTIMIZED)
    planner_frequency: 1.0           # Increased for more responsive planning
    progress_timeout: 300.0         # Reasonable timeout
    transform_tolerance: 0.5         # More lenient transform tolerance
    
    # Frontier detection (AGGRESSIVE SETTINGS)
    min_frontier_size: 0.01           # Smaller minimum to find more frontiers
    potential_scale: 1.0             # Reduced to be less picky about frontier size
    orientation_scale: 0.0           # Keep at 0 (orientation doesn't matter)
    gain_scale: 3.0                  # Higher gain scale for information reward
    
    # Goal selection (OPTIMIZED)
    frontier_travel_point: middle    # Try middle instead of closest
    min_distance: 0.1                # Reduced minimum distance
    
    # Additional parameters for thorough exploration
    same_frontier_dist: 0.5          # Distance threshold for considering frontiers the same
    frontier_blacklist_ratio: 0.25   # Ratio of frontier that must be black-listed before giving up
    
    # Recovery behavior parameters
    max_retries: 5                   # Maximum retries for failed goals
    retry_delay: 2.0                 # Delay between retries
    
    # Advanced frontier filtering
    min_frontier_cluster_size: 50     # Minimum points in a frontier cluster
    max_frontier_size: 100.0         # Maximum frontier size to consider