explore_node:
  ros__parameters:
    # Frame configuration
    robot_base_frame: base_link
    global_frame: map
    
    # Costmap topics (FIXED - was using wrong topics)
    costmap_topic: global_costmap/costmap
    costmap_updates_topic: global_costmap/costmap_updates
    
    # Exploration behavior
    return_to_init: true
    visualize: true
    
    # Timing parameters
    planner_frequency: 0.33          # Increased from 0.15 for better performance
    progress_timeout: 30.0
    transform_tolerance: 0.3
    
    # Frontier detection (IMPROVED)
    min_frontier_size: 0.5           # Reduced from 0.75 to find more frontiers
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    
    # Goal selection
    frontier_travel_point: closest
    min_distance: 0.3