# Autonomous Exploration Parameters
autonomous_explorer:
  ros__parameters:
    # Frontier Detection Parameters
    min_frontier_size: 5          # Minimum number of cells for a valid frontier
    min_frontier_distance: 0.5    # Minimum distance from robot to consider frontier (meters)
    
    # Navigation Parameters
    goal_timeout: 30.0            # Maximum time to reach a goal (seconds)
    exploration_timeout: 600.0    # Maximum total exploration time (seconds)
    
    # Frame IDs
    robot_frame: "base_link"      # Robot's base frame
    map_frame: "map"              # Map frame
    
    # Goal Selection Strategy
    goal_selection_strategy: "nearest"  # Options: "nearest", "largest", "hybrid"
    
    # Advanced Parameters
    frontier_filter_radius: 0.3   # Radius to filter clustered frontiers
    safety_distance: 0.2          # Safety distance from obstacles
    replan_frequency: 2.0         # How often to recheck frontiers (Hz)
    
    # Visualization
    publish_frontiers: true       # Publish frontier markers
    publish_goal_marker: true     # Publish current goal marker
    
    # Recovery Behaviors
    max_recovery_attempts: 3      # Maximum attempts to recover from failure
    recovery_timeout: 10.0        # Time to wait before retry (seconds)
    
    # Performance Tuning
    map_update_frequency: 1.0     # How often to process new maps (Hz)
    tf_timeout: 1.0               # TF lookup timeout (seconds)